# docker-compose.yml
version: '3.7'
services:
  database:
    container_name: docker-symfony-db
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    container_name: docker-symfony-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    user: ${LOCAL_USER}
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@127.0.0.1:${MYSQL_PORT}/${DATABASE_NAME}?serverVersion=5.7

  nginx:
    container_name: docker-symfony-nginx
    image: nginx:1.15.3-alpine
    restart: on-failure
    depends_on:
      - php

