# docker-compose.override.yml
version: '3.7'
services:
  php:
    volumes:
      - './apps/my-symfony-app/:/usr/src/app'

  nginx:
    volumes:
      - './apps/my-symfony-app/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 8080:80

  adminer:
    ports:
      - 8090:8080